refactor(IP Address): Update all IP Addresses in tests to use RFC-5735 TEST-NET-* addresses.
pypa/warehouse pull request #15470
Opened 2024-02-25 18:14 UTC by Mr-Sunglasses

fix: #13186

2024-02-25 19:30 UTC, Mr-Sunglasses commented
Hey @miketheman , as far as I've researched on the issue #13186 
The IP address ranges for *RFC-5735 TEST-NET-**

```
TEST-NET-1: 192.0.2.0/24
TEST-NET-2: 198.51.100.0/24
TEST-NET-3: 203.0.113.0/24
```

I've updated all the IP Addresses in `test/`

2024-02-26 15:15 UTC, miketheman reviewed
Nice work, a couple of comments inline to think about.

2024-02-28 09:32 UTC, Mr-Sunglasses commented on tests/conftest.py
> +    return "192.0.2.1"
Hey @miketheman I've some my research and changed them to [scope="session"](https://docs.pytest.org/en/8.0.x/how-to/fixtures.html#scope-sharing-fixtures-across-classes-modules-packages-or-session) , so they are dynamic now.

2024-02-28 09:34 UTC, Mr-Sunglasses commented
@miketheman I've made the changes you suggested me, let me know if there are any more changes to be made in this PR :)

2024-03-01 14:43 UTC, miketheman requested changes
@Mr-Sunglasses This is coming along nicely, thanks for continuing the effort!

There's a few more cases of non-replaced IP address strings - I haven't exhaustively identified each one, but we're getting closer!

2024-03-01 14:43 UTC, miketheman commented on tests/unit/utils/test_wsgi.py
> +        expected_remote_addr_hashed = calculate_hashed_value("1.2.3.4", "pepa")
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** Can you help me understand why we're back to using a 1.2.3.4 here?
In my head, all the `REMOTE_ADDR` entries above could be replaced by the `remove_addr` fixture, and the `REMOTE_ADDR_HASHED` below could be replaced with the `remote_addr_hashed` fixture, and the `calculate_hashed_value()` function could go away.‏

2024-03-01 14:43 UTC, miketheman commented on tests/conftest.py
> +@pytest.fixture(scope="function")
Shouldn't all of these be scoped to `session`, so they effectively become set once per test suite run?

```suggestion
@pytest.fixture(scope="session")
```

2024-03-01 14:43 UTC, miketheman commented on tests/conftest.py
> +        return None
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** How could `remote_addr` be `None`? Do we ever override the input to this fixture function, or should this condition be removed?

2024-03-01 14:43 UTC, miketheman commented on tests/unit/accounts/test_security_policy.py
> +                remote_addr="192.0.2.1",
These should also probably be replaced by `remote_addr`

2024-07-23 07:24 UTC, firefly9966 approved these changes

2025-02-06 08:29 UTC, aviral-bhardwaj commented
why this is still open

2026-07-12 16:39 UTC, closed without merging

2026-07-12 16:41 UTC, JacobCoffee commented
Abandoned and way behind. #20265 will take its place i guess