Drop the use of load_only() where no longer needed
pypa/warehouse pull request #3046
Opened 2018-02-23 20:03 UTC by dstufft

Since Release.description is not deferred by default, we no longer need to bend over backwards with load_only to attempt to minimize data. While the minimized queries are still *technically* more efficient since we're only pulling over exactly what we need, they are not meaningfully more efficient and are more likely to accidentally trigger N+1 query issues.

2018-02-23 20:40 UTC, di approved these changes

2018-02-24 02:11 UTC, ewdurbin requested changes
I think there's a good case for holding on to at least one of these optimizations, as it is hit by automated systems on a regular basis with heavy miss ratio (json api)

2018-02-24 02:11 UTC, ewdurbin commented on warehouse/legacy/api/json.py
> -               .options(Load(Release).load_only('version'))
quick local testing shows a 20-30% save for `cs18-sidecar` locally. I say we keep this one :)

2018-02-24 08:18 UTC, dstufft commented
@ewdurbin Changes made!

2018-02-24 18:58 UTC, ewdurbin approved these changes

2018-02-24 18:58 UTC, merged