Add eo locale to KNOWN_LOCALES mapping
pypa/warehouse pull request #9245
Opened 2021-03-17 17:32 UTC by phlostically

The eo locale (Esperanto) is 100% translated on [Weblate](https://hosted.weblate.org/projects/pypa/warehouse/eo/), and [should be added as a known locale](https://warehouse.readthedocs.io/translations.html#adding-a-newly-completed-translation).

2021-03-17 17:58 UTC, di requested changes
You're missing steps 3 and 4 from https://warehouse.readthedocs.io/translations.html#adding-a-newly-completed-translation here.

2021-03-17 19:08 UTC, phlostically commented
> You're missing steps 3 and 4 from https://warehouse.readthedocs.io/translations.html#adding-a-newly-completed-translation here.

I ran `make build-mos` but it didn’t produce any changes in the built files (`warehouse/locale/eo/messages.{mo,.po}`). Did I miss something? Log attached.
[log.txt](https://github.com/pypa/warehouse/files/6159070/log.txt)

2021-03-18 01:03 UTC, di approved these changes
Actually, I was wrong, the docs are out of date and step 3 and 4 are no longer necessary. Sorry for the confusion!

2021-03-18 01:32 UTC, merged

2021-03-18 01:32 UTC, di commented
Thanks!